config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :top, only: [:new]
  resources :promises, only: [:new]
  resources :laws, only: [:index, :show]
  resources :commerces, only: [:index, :show]
  resources :economicses, only: [:index, :show]
  resources :literatures, only: [:index, :show]
  resources :sciences, only: [:index, :show]
  resources :technos, only: [:index, :show]
  resources :users, only: [:show, :edit, :update]
  resources :deals, only: [:show, :destroy]
  resources :products, only: [:show, :edit, :update, :new, :create, :index, :destroy]do
   collection do
      post 'search'
    end
     resources :chats, only: [:show, :create, :new]do
       resources :chat_messages, only: [:new, :show, :create]
    end  
  end
  root 'top#index'
end

# git push heroku master

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_many :chat_messages
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :chat
  # belongs_to :user_id, :class_name => 'User', :foreign_key => 'user_id'  
 belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :chats


  enum faculty: { 法学部: 0, 商学部: 1, 経済学部: 2, 文学部: 3, 総合政策学部: 4, その他: 5}
  validates_presence_of :text_name, :image_url, :price, :detail
 # attr_accessible :image_url
  has_attached_file :image_url, styles: { medium: "300x300>", thumb: "100x100>" },:storage => :s3,
:s3_credentials => "#{Rails.root}/config/s3.yml",
:path => ":attachment/:id/:style.:extension"
  # , default_url: "/system/missing/:style/missing.jpg"
 validates_attachment_content_type :image_url, content_type: ["image/jpg","image/jpeg","image/png"]
  # validates_attachment :image_url, content_type: ["image/jpg","image/jpeg","image/png"]
  # presence: true,
  #   content_type: { content_type: ["image/jpg", "image/png"] },
  #   size: { less_than: 2.megabytes }
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  # validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
  # validates :text_name, presence: true
  # validates :text_name, presence: true
  # validate :add_error_sample
  #   def add_error_sample
  #     nameが空のときにエラーメッセージを追加する
  #     if text_name.empty?
  #       errors.add(:text_name, "に関係するエラーを追加")
  #       errors[:base] << "モデル全体に関係するエラーを追加"
  #     end
  # validates_presence_of :text_name, :message => "モデル全体に関係するエラーを追加"
  #   end
# validates_acceptance_of :terms_of_service
#  validates_acceptance_of :text_name, message: '記入してください'
def authenticated_image_url(style)
    image_url.s3_object(style).url_for(:read, :secure => true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"},:storage => :s3,
:s3_credentials => "#{Rails.root}/config/s3.yml",
:path => ":attachment/:id/:style.:extension"


  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]


  def authenticated_image_url(style)
    avatsr.s3_object(style).url_for(:read, :secure => true)
  end



  has_many :products
  has_many :chats
  has_many :chat_messages
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @chat = Chat.new
  end  
  def show
     @product = Product.find(params[:product_id])
  end
  def create
    @product = Product.find(params[:product_id])
    if Chat.find_by(seller_id: params[:seller_id], buyer_id: params[:buyer_id], product_id: params[:product_id]).present?
      @chat = Chat.find_by(seller_id: params[:seller_id], buyer_id: params[:buyer_id], product_id: params[:product_id])
      redirect_to new_product_chat_chat_message_url(params[:product_id], @chat.id) 
      else
      @chat = Chat.create(create_params)
      redirect_to new_product_chat_chat_message_url(params[:product_id], @chat.id) 
    end
  end  

  private
  def create_params
    params.permit(:buyer_id, :seller_id, :product_id)
  end
end

app/controllers/commerces_controller.rb
class CommercesController < ApplicationController
    before_action :authenticate_user!, except: :index
  def index
    @products = Product.商学部.order('id DESC').page(params[:page]).per(9)
  end

  def show
     @products = Product.find(params[:id])
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def show
    @chats_contents = Chat.where(["buyer_id = ? or seller_id = ?", current_user.id, current_user.id]).order('created_at DESC')
    @products = @chats_contents.product
  end
  def destroy
    @chat = Chat.find(params[:id])
    if @chat.buyer_id == current_user.id || @chat.seller_id == current_user.id
           @chat.destroy
           
    end
    redirect_to controller: :deals, action: :show
  end
end

app/controllers/laws_controller.rb
class LawsController < ApplicationController
    before_action :authenticate_user!, except: :index
  def index
    @products = Product.法学部.order('id DESC').page(params[:page]).per(9)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    current_user.update(update_params)
    redirect_to action: :show
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :major, :introduce, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/economicses_helper.rb
module EconomicsesHelper
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/helpers/literatures_helper.rb
module LiteraturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sciences_helper.rb
module SciencesHelper
end

app/helpers/technos_helper.rb
module TechnosHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commerces/index.html.erb
<div class="center-block">
<div class="top_header_product">
  <div class="container">
      <div class="row">
         <div class=" .col-xs-6 .col-xs-offset-3">

              <div class="panel panel-default">


         <div class="col-md-12">
                    <% @products.each do |product|%>

         <div class="col-md-4">
                     <div class="row">
                    <!--   <div class="col-sm-6 col-md-4"> -->
                        <div class="thumbnail">
                         
                          <%= image_tag  (product.authenticated_image_url(:medium)) %>
                          <div class="caption">
                          　 <h4>大学:<%= product.univercity %></h4>
                            <h4>教科書:<%= product.text_name %></h4>
                            <h4>教授:<%= product.professor %></h4>
                            <p>値段:<%= product.price %>円</p>
                            
                             <p><%= link_to "詳細を見る",  commerce_path(product.id) , class: "btn btn-primary", role: "button"%></p>
                          </div>
                        </div>
                      </div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
                    </div>
                 <% end %>


                        </div>
                      <%= paginate(@products) %>
                   </div>

              </div>

          </div>
      </div>


</div>

  </div>

app/views/commerces/show.html.erb
<div class="center-block">
  <div class="top_header_show">

    <div class="container">
      <div class="row" >
        <div class=".col-xs-6 .col-xs-offset-2">
          <div class="thumbnail">
            <%= image_tag  @products.image_url %>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
            <div class="caption">
              <h3>大学名:<%= @products.univercity %></h3>

              <h3>教科書名 : <%= @products.text_name %></h3>
              <h3>教授名 : <%= @products.professor %></h3>
              <h3>価格　: <%= @products.price %></h3>
              <h3>商品詳細 : <%= @products.detail %></h3>
              <h3>学部名 : <%= @products.faculty %></h3>
              <h3>配送負担 : <%= @products.sent_price %></h3>
              <h3>配送方法 : <%= @products.sent_method %></h3>

              <h2><%= link_to "出品者情報はこちら！", user_path(@products.user) %></h2>
              <%= link_to "購入する",  new_product_chat_path(params[:id]) , class: "btn btn-primary", role: "button"%>
            </div> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>


<!--  <p>%= link_to '購入する', hogehoge_path(buyer_id: 15, seller_id: 41)
 -->