config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :top, only: [:new]
  resources :promises, only: [:new]
  resources :laws, only: [:index, :show]
  resources :commerces, only: [:index, :show]
  resources :economicses, only: [:index, :show]
  resources :literatures, only: [:index, :show]
  resources :sciences, only: [:index, :show]
  resources :technos, only: [:index, :show]
  resources :users, only: [:show, :edit, :update]
  resources :deals, only: [:show, :destroy]
  resources :products, only: [:show, :edit, :update, :new, :create, :index, :destroy]do
   collection do
      post 'search'
    end
     resources :chats, only: [:show, :create, :new]do
       resources :chat_messages, only: [:new, :show, :create]
    end  
  end
  root 'top#index'
end

# git push heroku master

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_many :chat_messages
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :chat
  # belongs_to :user_id, :class_name => 'User', :foreign_key => 'user_id'  
 belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :chats


  enum faculty: { 法学部: 0, 商学部: 1, 経済学部: 2, 文学部: 3, 総合政策学部: 4, その他: 5}
  validates_presence_of :text_name, :image_url, :price, :detail
 # attr_accessible :image_url
  has_attached_file :image_url, styles: { medium: "300x300>", thumb: "100x100>" },:storage => :s3,
:s3_credentials => "#{Rails.root}/config/s3.yml",
:path => ":attachment/:id/:style.:extension"
  # , default_url: "/system/missing/:style/missing.jpg"
 validates_attachment_content_type :image_url, content_type: ["image/jpg","image/jpeg","image/png"]
  # validates_attachment :image_url, content_type: ["image/jpg","image/jpeg","image/png"]
  # presence: true,
  #   content_type: { content_type: ["image/jpg", "image/png"] },
  #   size: { less_than: 2.megabytes }
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  # validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
  # validates :text_name, presence: true
  # validates :text_name, presence: true
  # validate :add_error_sample
  #   def add_error_sample
  #     nameが空のときにエラーメッセージを追加する
  #     if text_name.empty?
  #       errors.add(:text_name, "に関係するエラーを追加")
  #       errors[:base] << "モデル全体に関係するエラーを追加"
  #     end
  # validates_presence_of :text_name, :message => "モデル全体に関係するエラーを追加"
  #   end
# validates_acceptance_of :terms_of_service
#  validates_acceptance_of :text_name, message: '記入してください'
def authenticated_image_url(style)
    image_url.s3_object(style).url_for(:read, :secure => true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"},:storage => :s3,
:s3_credentials => "#{Rails.root}/config/s3.yml",
:path => ":attachment/:id/:style.:extension"


  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]


  def authenticated_image_url(style)
    avatsr.s3_object(style).url_for(:read, :secure => true)
  end



  has_many :products
  has_many :chats
  has_many :chat_messages
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @chat = Chat.new
  end  
  def show
     @product = Product.find(params[:product_id])
  end
  def create
    @product = Product.find(params[:product_id])
    if Chat.find_by(seller_id: params[:seller_id], buyer_id: params[:buyer_id], product_id: params[:product_id]).present?
      @chat = Chat.find_by(seller_id: params[:seller_id], buyer_id: params[:buyer_id], product_id: params[:product_id])
      redirect_to new_product_chat_chat_message_url(params[:product_id], @chat.id) 
      else
      @chat = Chat.create(create_params)
      redirect_to new_product_chat_chat_message_url(params[:product_id], @chat.id) 
    end
  end  

  private
  def create_params
    params.permit(:buyer_id, :seller_id, :product_id)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def show
    @chats_contents = Chat.where(["buyer_id = ? or seller_id = ?", current_user.id, current_user.id]).order('created_at DESC')
    @products = @chats_contents.product
  end
  def destroy
    @chat = Chat.find(params[:id])
    if @chat.buyer_id == current_user.id || @chat.seller_id == current_user.id
           @chat.destroy
           
    end
    redirect_to controller: :deals, action: :show
  end
end

app/controllers/laws_controller.rb
class LawsController < ApplicationController
    before_action :authenticate_user!, except: :index
  def index
    @products = Product.法学部.order('id DESC').page(params[:page]).per(9)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    current_user.update(update_params)
    redirect_to action: :show
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :major, :introduce, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/economicses_helper.rb
module EconomicsesHelper
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/helpers/literatures_helper.rb
module LiteraturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sciences_helper.rb
module SciencesHelper
end

app/helpers/technos_helper.rb
module TechnosHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/deals/show.html.erb
<div class="center-block">
<div class="top_header_product">
  <div class="container">
      <div class="row">
         <div class=" .col-xs-6 .col-xs-offset-3">
              <div class="panel panel-default">
         <div class="col-md-12">
                    <% @chats_contents.each do |chat|%>
         <div class="col-md-4">
                     <div class="row">
                    <!--   <div class="col-sm-6 col-md-4"> -->
                        <div class="thumbnail">
                        
                         <%= image_tag  (chat.product.authenticated_image_url(:medium)) %>
                          <div class="caption">
                          　 <h4>大学:<%= chat.product.univercity %></h4>
                            <h4>教科書:<%= chat.product.text_name %></h4>
                            <h4>教授:<%= chat.product.professor %></h4>
                            <p>値段:<%= chat.product.price %>円</p>
                            <p><%= link_to "メッセージを見る", new_product_chat_chat_message_path(chat.product.id, chat.id) , class: "btn btn-primary", role: "button" %></p>
                            <p><%= link_to "削除する", deal_path(chat.id), method: :delete,  class: "btn btn-primary", role: "button", data: { confirm: "本当に削除してよろしいですか？",
                                                                                   "commit" => "削除する",
                                                                                   "cancel" => "やっぱりやめる",
                                                                                   }, title: "削除の確認"%></p>
                          </div>
                        </div>
                      </div>
                    </div>
                 <% end %>
                        </div>
                   </div>
              </div>
          </div>
      </div>
</div>

app/views/laws/index.html.erb
<div class="center-block">
<div class="top_header_product">
  <div class="container">
      <div class="row">
         <div class=" .col-xs-6 .col-xs-offset-3">

              <div class="panel panel-default">

         <div class="col-md-12">
         
                    <% @products.each do |product|%>

         <div class="col-md-4">
                     <div class="row">
                    <!--   <div class="col-sm-6 col-md-4"> -->
                        <div class="thumbnail">
                         <%= image_tag  (product.authenticated_image_url(:medium)) %>

                          <div class="caption">
                          　 <h4>大学:<%= product.univercity %></h4>
                            <h4>教科書:<%= product.text_name %></h4>
                            <h4>教授:<%= product.professor %></h4>
                            <p>値段:<%= product.price %>円</p>
                            <p><%= link_to "詳細を見る", law_path(product.id) , class: "btn btn-primary", role: "button"%></p>
                          </div>
                        </div>
                        
                      </div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
                    </div>

                 <% end %>

                        </div>
                      <%= paginate(@products) %>
                   </div>

              </div>

          </div>
      </div>


</div>

app/views/laws/show.html.erb
<div class="center-block">
  <div class="top_header_show">
    <div class="container">
      <div class="row" >
        <div class=".col-xs-6 .col-xs-offset-2">
          <div class="thumbnail">
            <%= image_tag  @product.image_url %>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
            <div class="caption">
              <h3>大学名:<%= @product.univercity %></h3>

              <h3>教科書名 : <%= @product.text_name %></h3>
              <h3>教授名 : <%= @product.professor %></h3>
              <h3>価格　: <%= @product.price %></h3>
              <h3>商品詳細 : <%= @product.detail %></h3>
              <h3>学部名 : <%= @product.faculty %></h3>
              <h3>配送負担 : <%= @product.sent_price %></h3>
              <h3>配送方法 : <%= @product.sent_method %></h3>

              <h2><%= link_to "出品者情報はこちら！", user_path(@product.user) %></h2>
              <%= link_to "購入する",  new_product_chat_path(@product.id) , class: "btn btn-primary", role: "button"%>
            </div> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>


<!--  <p>%= link_to '購入する', hogehoge_path(buyer_id: 15, seller_id: 41)
 -->

app/views/top/index.html.erb
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header" style = "background: url(<%= asset_path('intro-bg.jpg') %>) no-repeat center center;">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                    <h1><strong>UNIBOOK</strong></h1>
                        <h3>教科書を安く買おう</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                             <%= link_to "新規登録", new_user_registration_path, class: "btn btn-default btn-lg fa fa-twitter fa-fw"  %>
                 <!-- 
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">新規登録</span></a> -->
                            </li>
                            <li>
                             <%= link_to "ログイン", new_user_session_path, class: "btn btn-default btn-lg fa fa-twitter fa-fw"  %>
                                <!-- <a href="#" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">ログイン</span></a> -->
                            </li>

                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

  <a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">UNIBOOKとは？</h2>
                    <p class="lead">中大生のための教科書フリマサービスです。もう後輩に教科書をあげる必要も、高い教科書を新しく買う必要なんてありません。UNIBOOKは教科書を売りたい上級生と教科書を買いたい下級生が繋げ、取引をすることが出来ます。</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag  "bg.jpg", class: "img-responsive" %>

                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">UNIBOOKの特徴</h2>
                    <p class="lead">中央大学生のためのサービスです。売りたい人は出品して連絡を待つだけ、買いたい人は欲しい教科書を選ぶだけでメッセージでやりとりをすることが出来ます。同じ大学に通うので授業に行ったついでに直接取引も可能！授業の内容を先輩から教えてもらえるなんてことも！</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">

                    <%= image_tag  "ipad.png", class: "img-responsive" %>

                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">手数料が全て０円！</h2>
                    <p class="lead">簡単に取引することができるだけではありません。出品・購入はもちろん売れた時も手数料は無料！商品の送る方法から価格まで、あなただけの出品ができます。</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                     <%= image_tag  "portfolio-1.jpg", class: "img-responsive" %>

                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

  <a  name="contact"></a>
    <div class="banner" style="background: url(<%= asset_path('banner-bg.jpg') %>) no-repeat center center;">


        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>教科書を安く手にいれよう！</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-default btn-lg fa fa-twitter fa-fw"  %>
                          <!--   <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">新規登録</span></a> -->
                        </li>
                        <li>
                          <!--   <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">ログイン</span></a> -->
                            <%= link_to "ログイン", new_user_session_path, class: "btn btn-default btn-lg fa fa-twitter fa-fw"  %>
                        </li>

                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->

app/views/top/new.html.erb
<div class="center-block">
  <div class="top_header_product">
    <div class="container">
      <div class="row">
         <div class=" .col-xs-6 .col-xs-offset-3">
           <div class="panel panel-default">

  　　　　　　　　<h2>出品者との取引の流れ</h2>
               <h3>購入者</h3>
  　　　　　　　　　<ul>
                  <li>１.欲しい商品を見つけたら購入ボタンを押しましょう。</li><br>
                  <li>２.出品者にメッセージを送ってみましょう(よろしくお願いします、初めまして等)。</li><br>
                  <li>３.メッセージで取引内容の確認をしましょう（商品の金額、発送方法、振込先等）。</li><br>
                  <li>４.代金の振込先、または取引の場所を話し合いメッセージで決めてください。</li><br>
                  <li>５.お金の振込、商品の受け取りが確認できたらメッセージを送りましょう。</li><br>
                  <li>６.取引が終わったらマイページの取引中にある削除というボタンを押してください。</li>
                 </ul>
                 <br><br><br>
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
               <h3>出品者</h3>
  　　　　　　　　　<ul>
                  <li>１.購入者からメッセージがきたら返信しましょう(よろしくお願いします、初めまして等)。</li><br>
                  <li>２.取引内容の確認をしましょう（商品の金額、発送方法、振込先等）。</li><br>
                  <li>３.代金の振込先、または取引の場所を話し合いメッセージで決めてください。</li><br>
                  <li>４.お金の振込、商品の受け取りが確認できたらメッセージを送りましょう。</li><br>
                  <li>５.取引が終わったらマイページの取引中にある削除というボタンを押してください。</li>
                 </ul>
                 <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>