config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :top, only: [:new]
  resources :promises, only: [:new]
  resources :laws, only: [:index, :show]
  resources :commerces, only: [:index, :show]
  resources :economicses, only: [:index, :show]
  resources :literatures, only: [:index, :show]
  resources :sciences, only: [:index, :show]
  resources :technos, only: [:index, :show]
  resources :users, only: [:show, :edit, :update]
  resources :deals, only: [:show, :destroy]
  resources :products, only: [:show, :edit, :update, :new, :create, :index, :destroy]do
   collection do
      post 'search'
    end
     resources :chats, only: [:show, :create, :new]do
       resources :chat_messages, only: [:new, :show, :create]
    end  
  end
  root 'top#index'
end

# git push heroku master

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_many :chat_messages
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :chat
  # belongs_to :user_id, :class_name => 'User', :foreign_key => 'user_id'  
 belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :chats


  enum faculty: { 法学部: 0, 商学部: 1, 経済学部: 2, 文学部: 3, 総合政策学部: 4, その他: 5}
  validates_presence_of :text_name, :image_url, :price, :detail
 # attr_accessible :image_url
  has_attached_file :image_url, styles: { medium: "300x300>", thumb: "100x100>" },:storage => :s3,
:s3_credentials => "#{Rails.root}/config/s3.yml",
:path => ":attachment/:id/:style.:extension"
  # , default_url: "/system/missing/:style/missing.jpg"
 validates_attachment_content_type :image_url, content_type: ["image/jpg","image/jpeg","image/png"]
  # validates_attachment :image_url, content_type: ["image/jpg","image/jpeg","image/png"]
  # presence: true,
  #   content_type: { content_type: ["image/jpg", "image/png"] },
  #   size: { less_than: 2.megabytes }
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  # validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
  # validates :text_name, presence: true
  # validates :text_name, presence: true
  # validate :add_error_sample
  #   def add_error_sample
  #     nameが空のときにエラーメッセージを追加する
  #     if text_name.empty?
  #       errors.add(:text_name, "に関係するエラーを追加")
  #       errors[:base] << "モデル全体に関係するエラーを追加"
  #     end
  # validates_presence_of :text_name, :message => "モデル全体に関係するエラーを追加"
  #   end
# validates_acceptance_of :terms_of_service
#  validates_acceptance_of :text_name, message: '記入してください'
def authenticated_image_url(style)
    image_url.s3_object(style).url_for(:read, :secure => true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"},:storage => :s3,
:s3_credentials => "#{Rails.root}/config/s3.yml",
:path => ":attachment/:id/:style.:extension"


  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]


  def authenticated_image_url(style)
    avatsr.s3_object(style).url_for(:read, :secure => true)
  end



  has_many :products
  has_many :chats
  has_many :chat_messages
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @chat = Chat.new
  end  
  def show
     @product = Product.find(params[:product_id])
  end
  def create
    @product = Product.find(params[:product_id])
    if Chat.find_by(seller_id: params[:seller_id], buyer_id: params[:buyer_id], product_id: params[:product_id]).present?
      @chat = Chat.find_by(seller_id: params[:seller_id], buyer_id: params[:buyer_id], product_id: params[:product_id])
      redirect_to new_product_chat_chat_message_url(params[:product_id], @chat.id) 
      else
      @chat = Chat.create(create_params)
      redirect_to new_product_chat_chat_message_url(params[:product_id], @chat.id) 
    end
  end  

  private
  def create_params
    params.permit(:buyer_id, :seller_id, :product_id)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def show
    @chats_contents = Chat.where(["buyer_id = ? or seller_id = ?", current_user.id, current_user.id]).order('created_at DESC')
    @products = @chats_contents.product
  end
  def destroy
    @chat = Chat.find(params[:id])
    if @chat.buyer_id == current_user.id || @chat.seller_id == current_user.id
           @chat.destroy
           
    end
    redirect_to controller: :deals, action: :show
  end
end

app/controllers/laws_controller.rb
class LawsController < ApplicationController
    before_action :authenticate_user!, except: :index
  def index
    @products = Product.法学部.order('id DESC').page(params[:page]).per(9)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: :new
  def index
    @products = current_user.products.order('id DESC').page(params[:page]).per(9)
  end  
  def new
    @product = Product.new
  end
  def create
    @product = Product.create(create_params)
  end
  def edit
     @product = Product.find(params[:id])
  end
  
  def update
     @product = Product.find(params[:id])
    @product.update(update_params)
    redirect_to action: :index
  end

  def destroy
    @product = Product.find(params[:id])
    @chats = Chat.where(product_id: params[:id])

    @chat_messages = ChatMessage.where(product_id: params[:id])

      if @product.user_id == current_user.id
         @product.destroy
      end
      if @product.user_id == current_user.id && @chats.exists? 
          @chats.each do |chat| 
          chat.destroy
          end 
      end
      if   @product.user_id == current_user.id && @chat_messages.exists?
         @chat_messages.each do |chat_message|
         chat_message.destroy
         end
      end
       redirect_to controller: :products, action: :index
  end


  def search
 
      @products = Product.where('text_name LIKE(?)', "%#{params[:q]}%").order('id DESC').limit(16).page(params[:page]).per(9)
  end

  private
  def create_params
     params.require(:product).permit(:image_url, :price, :detail, :professor, :faculty, :text_name, :sent_price, :sent_method, :univercity).merge(user_id: current_user.id)

  end


  def update_params
    params.require(:product).permit(:image_url, :price, :detail, :professor, :faculty, :text_name, :sent_price, :sent_method, :univercity).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    current_user.update(update_params)
    redirect_to action: :show
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :major, :introduce, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/economicses_helper.rb
module EconomicsesHelper
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/helpers/literatures_helper.rb
module LiteraturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sciences_helper.rb
module SciencesHelper
end

app/helpers/technos_helper.rb
module TechnosHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/create.html.erb
<div class="top_header">
  <div class="container">
      <div class="row">
         <div class="col-lg-6 col-md-offset-6">

              <div class="panel panel-default">
                  <div class="panel-heading">
                    </div>
                      <div class="panel-body">
                        投稿が完了しました</br>
                        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
                        <%= link_to "トップページに戻る", root_path %>
                    </div>
                      <div class="panel-footer">
                      </div>
              </div>
          </div>
      </div>
  </div>

</div>

app/views/products/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
      <%= link_to "投稿一覧へ戻る", </a>
    </div>
  </div>

app/views/products/edit.html.erb
  <div class="top_header">
  <div class="container">
      <div class="row">
          <div class="col-md-4 col-md-offset-7">
              <div class="panel panel-default">
                  <div class="panel-heading">
                    ユーザー情報</div>
                      <div class="panel-body">

                      <%= form_for @product  do |f| %>
                        <h2>商品の説明</h2>
                          <div class="form-group">
                            <div class="col-lg-12">
                             <p>教科書画像</p>
                                <div class="form-group file">
                                  <%= f.file_field :image_url, class: "form-control floating-label", placeholder: "画像アップロード" %>
                                </div>
                            </div>

                            <div class="col-lg-12">
                              <p>値段</p>
                              <%= f.text_field :price, placeholder: "値段", class: "form-control" %>
                            </div>

                            <div class="col-lg-12">
                              <p>大学名</p>
                              <%= f.text_field :univercity, placeholder: "大学名", class: "form-control" %>
                            </div>

                            <div class="col-lg-12">
                              <p>教科書名</p>
                              <%= f.text_field :text_name, placeholder: "教科書名", class: "form-control" %>
                            </div>




                            <div class="col-lg-12">
                              <p>詳細</p>
                              <%= f.text_field :detail, placeholder: "商品詳細", class: "form-control" %>
                            </div>

                            <div class="col-lg-12">
                              <p>教授名</p>
                              <%= f.text_field :professor, placeholder: "教授名", class: "form-control" %>
                            </div>

                             <div class="col-lg-12">
                                <p>学部</p>
                                <%= f.select :faculty , [['法学部','法学部'],['商学部','商学部'],['経済学部','経済学部'],['文学部','文学部'],['総合政策学部','総合政策学部'],['その他','その他']] %>
                             </div>

                             <div class="col-lg-12">
                               <p>送料負担</p>
                               <%= f.select :sent_price , [['販売者負担','販売者負担'],['買い手負担','買い手負担'],['大学で手渡し0円','大学で手渡し0円']] %>
                             </div>

                             <div class="col-lg-12">
                               <p>配送方法</p>
                               <%= f.select :sent_method , [['大学で手渡し0円','大学で手渡し0円'],['配送(約200~300円,定形外郵便物,ゆうパック等)','配送(約200~300円,定形外郵便物,ゆうパック等)'],['配送(約300~500円,レターパック,ヤマト運輸等)','配送(約300~500円,レターパック,ヤマト運輸等']] %>

                             </div>


                               <%= f.submit "更新する", class: "btn btn-primary withripple maipe-ji" %>
                          </div>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
                    <% end %>


                      <!-- <div class="actions">
                         <button type="button" class="btn btn-primary"><%= link_to "更新する", edit_user_path(current_user) %></button>

                      </div> -->

                      </div>


                      <div class="panel-footer">
                      </div>
              </div>
          </div>
      </div>
  </div>

  </div>

app/views/products/index.html.erb
<div class="center-block">
<div class="top_header_product">
  <div class="container">
      <div class="row">
         <div class=" .col-xs-6 .col-xs-offset-3">

              <div class="panel panel-default">

         <div class="col-md-12">
         
                    <% @products.each do |product|%>

         <div class="col-md-4">
                     <div class="row">
                    <!--   <div class="col-sm-6 col-md-4"> -->
                        <div class="thumbnail">
                         <%= image_tag  product.image_url %>
                         <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
                          <div class="caption">
                          　 <h4>大学:<%= product.univercity %></h4>
                            <h4>教科書:<%= product.text_name %></h4>
                            <h4>教授:<%= product.professor %></h4>
                            <p>値段:<%= product.price %>円</p>
                            <p><%= link_to "編集する", edit_product_path(product.id) , class: "btn btn-primary", role: "button"%></p>
                            <p><%= link_to "削除する", product_path(product.id), method: :delete,  class: "btn btn-primary", role: "button", data: { confirm: "本当に削除してよろしいですか？",
                                                                                   "commit" => "削除する",
                                                                                   "cancel" => "やっぱりやめる",
                                                                                   }, title: "削除の確認"%></p>

                          </div>
                        </div>
                      </div>

                    </div>

                 <% end %>

                        </div>
                      <%= paginate(@products) %>
                   </div>

              </div>

          </div>
      </div>


</div>

app/views/products/new.html.erb
<div class="top_header">
  <div class="container">
      <div class="row">
         <div class="col-lg-6 col-md-offset-6">

              <div class="panel panel-default">
                  <div class="panel-heading">
                    出品情報</div>
                      <div class="panel-body">



                     <% if @product.errors.any? %>

                      <div id="error_explanation">
                        <h2><%= @product.errors.count %>件のエラーがあります。</h2>

                        <ul>
                        <% @product.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>





                  <%= form_for @product do |f| %>
                        <h2>商品の説明</h2>
                          <div class="form-group">
                            <div class="col-lg-12">
                             <p>教科書画像</p>
                                <div class="form-group file">

                                  <%= f.file_field :image_url, class: "form-control floating-label", placeholder: "画像アップロード" %>
                                </div>
                            </div>


                            <div class="col-lg-12">
                              <p>値段</p>
                              <%= f.text_field :price, placeholder: "値段", class: "form-control" %>
                            </div>

                            <div class="col-lg-12">
                              <p>大学名</p>
                              <%= f.text_field :univercity, placeholder: "大学名", class: "form-control" %>
                            </div>

                            <div class="col-lg-12">
                              <p>教科書名</p>
                              <%= f.text_field :text_name, placeholder: "教科書名", class: "form-control" %>
                            </div>




                            <div class="col-lg-12">
                              <p>詳細</p>
                              <%= f.text_field :detail, placeholder: "商品詳細", class: "form-control" %>
                            </div>

                            <div class="col-lg-12">
                              <p>教授名</p>
                              <%= f.text_field :professor, placeholder: "教授名", class: "form-control" %>
                            </div>

                             <div class="col-lg-12">
                                <p>学部</p>
                                <%= f.select :faculty , [['法学部','法学部'],['商学部','商学部'],['経済学部','経済学部'],['文学部','文学部'],['総合政策学部','総合政策学部'],['その他','その他']] %>
                             </div>

                             <div class="col-lg-12">
                               <p>送料負担</p>
                               <%= f.select :sent_price , [['販売者負担','販売者負担'],['買い手負担','買い手負担'],['大学で手渡し0円','大学で手渡し0円']] %>
                             </div>

                             <div class="col-lg-12">
                               <p>配送方法</p>
                               <%= f.select :sent_method , [['大学で手渡し0円','大学で手渡し0円'],['配送(約200~300円,定形外郵便物,ゆうパック等)','配送(約200~300円,定形外郵便物,ゆうパック等)'],['配送(約300~500円,レターパック,ヤマト運輸等)','配送(約300~500円,レターパック,ヤマト運輸等']] %>
                             </div>


                               <%= f.submit "出品する", class: "btn btn-primary withripple maipe-ji" %>
                          </div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

                    <% end %>


                      </div>


                      <div class="panel-footer">
                      </div>
              </div>
          </div>
      </div>
  </div>

</div>

app/views/products/search.html.erb
<div class="center-block">
<div class="top_header_product">
  <div class="container">
      <div class="row">
         <div class=" .col-xs-6 .col-xs-offset-3">

              <div class="panel panel-default">


         <div class="col-md-12">
                    <% @products.each do |product|%>

         <div class="col-md-4">
                     <div class="row">
                    
                        <div class="thumbnail">
                         <%= image_tag  product.image_url %>
                         <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
                          <div class="caption">
                            <h4><%= product.text_name %></h4>
                            <h4><%= product.professor %></h4>
                            <p><%= product.price %>円</p>
                            <p><%= link_to "詳細を見る", "#" , class: "btn btn-primary", role: "button"%></p>
                          </div>
                        </div>
                      </div>

                    </div>

                 <% end %>

                        </div>
                      <%= paginate(@products) %>
                   </div>

              </div>

          </div>
      </div>


</div>

  </div>

app/views/products/show.html.erb
<div class="center-block">
  <div class="top_header_show">

    <div class="container">
      <div class="row" >
        <div class=".col-xs-6 .col-xs-offset-2">
          <div class="thumbnail">
            <%= image_tag  @product.image_url %>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ブログ　コンテンツ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9875563038621390"
     data-ad-slot="3516785266"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
            <div class="caption">
              <h3>大学名:<%= @product.univercity %></h3>

              <h3>教科書名 : <%= @product.text_name %></h3>
              <h3>教授名 : <%= @product.professor %></h3>
              <h3>価格　: <%= @product.price %></h3>
              <h3>商品詳細 : <%= @product.detail %></h3>
              <h3>学部名 : <%= @product.faculty %></h3>
              <h3>配送負担 : <%= @product.sent_price %></h3>
              <h3>配送方法 : <%= @product.sent_method %></h3>

              
              <%= link_to "編集する",  new_product_chat_path(@product.id) , class: "btn btn-primary", role: "button"%>
              
            </div> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>


<!--  <p>%= link_to '購入する', hogehoge_path(buyer_id: 15, seller_id: 41)
 -->
  